# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f02823fe2a4328bc72006d733d3891eb4e96249ae1fe31094bcdecb97b34bdbb5551bbd5a63e43170d32646d25be6dca827279626999f7630f91b910de5612

test:
  secret_key_base: 5801e1874a1fb5a173505f141af1a46f5a82e6e83fc87766ee2f26f836c8638ca8ea3d5a1b04188901d9a715a6494f74cc5491886df8adcfc40a93e3a6032f0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
